### PR TITLE
chore: use Uniswap ESLint config

### PR DESCRIPTION
**Pull request by grabbou**
## Background

While at it, decided to replace custom ESLint config with our official Uniswap one. 

## Changes

- React plugins removed as they're not used, using Node environment instead
- `typescript-sort-keys/string-enum` is temporarily gone, will work on adding it and releasing in the next ESLint config version
-  `naming-convention` is temporarily gone, will work on adding it and releasing in the next ESLint config version, most likely with other naming convention patterns
- Removed `package*` from `.gitignore` as it was hiding `package.json` in VSCode (and also, I think it's not really related to this particular project)

## Testing

Unit tests should pass

### CODE REVIEW

**Comment by grabbou** [comment]
Feel free to merge this as is or wait for the next ESLint config release.

**Comment by adjkant** [comment]
Going to hold waiting for the next version but otherwise looks good!

**Comment by adjkant** [comment]
@zzmp I thought we were waiting for `typescript-sort-keys/string-enum` and `naming-convention` here right? Are those good to go?

**Comment by adjkant** [comment]
Closing this as will migrate once brought into the monorepo

**Pull request closed without merging**
