### PR TITLE
feat: add InterfaceEvent.UNISWAP_WALLET_APP_DOWNLOAD_OPENED for tracking app opens

### PR DESCRIPTION
**Pull request by natew**
For this PR:

https://github.com/Uniswap/interface/pull/6732

Adds tracking for app download links

### CODE REVIEW

**Comment by adjkant** [comment]
I just reviewed the other PR, it seems like there's some odd stuff going on with the analytics on these so wanna get clarification before adding another event! In general we should be able to reuse an existing event and define a new element ideally

**Comment by tinaszheng** [comment]
@adjkant what do you mean?

**Comment by adjkant** [comment]
> @adjkant what do you mean?

I'm a bit unclear what this event is tracking / where it's meant to be triggered from. It also looks like in some cases it will log a plain element clicked event with no element so wanna get that sorted as well!

**Comment by natew** [comment]
@adjkant reason I added a new event is because the existing one is named `UNISWAP_WALLET_MICROSITE_OPENED` which is very specific to opening the wallet site, whereas we are opening the app store download link directly in the other case.

do we prefer to do something like change `UNISWAP_WALLET_MICROSITE_OPENED` to `OPEN_LINK` and then have tags or something like that instead?

otherwise i feel like this name works in terms of being just as specific as the other names.

**Comment by adjkant** [comment]
Got it, I think the event makes sense! I was a bit confused by the usage but I think once we fix that this event will make sense

**Review by adjkant — APPROVED** [review]
need to sort alphabetically to pass CI but otherwise LGTM!

**Pull request merged**
